# Generated by Django 4.0.2 on 2022-04-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sentMail',
            field=models.BooleanField(default=False),
        ),
    ]
